# Generated by Django 5.2.8 on 2025-11-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dish_delete_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='district',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
