# Generated by Django 5.2.8 on 2025-12-04 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_instruction_recipe_remove_recipe_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppinglistitem',
            unique_together={('user', 'name')},
        ),
    ]
