# Generated by Django 5.2.5 on 2025-11-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('food_type', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], default='veg', max_length=10)),
                ('meal_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='afternoon', max_length=20)),
                ('occasion_type', models.CharField(choices=[('school/office', 'School/Office'), ('festival', 'Festival'), ('relatives', 'Relatives'), ('regular', 'Regular')], default='regular', max_length=20)),
                ('prep_time', models.PositiveIntegerField(help_text='Time in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(help_text="e.g., '100g', '2', '1 tsp'", max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeManagement.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeManagement.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='RecipeManagement.RecipeIngredient', to='RecipeManagement.ingredient'),
        ),
    ]
