# Generated by Django 5.2.8 on 2025-11-24 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('instructions', models.TextField()),
                ('image', models.ImageField(upload_to='recipes/')),
                ('category', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], max_length=20)),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('recipe_type', models.CharField(choices=[('sweet', 'Sweet'), ('meals', 'Meals'), ('side', 'Side Dish'), ('snacks', 'Snacks')], max_length=20)),
                ('cook_time', models.CharField(help_text="e.g., '25 min', '1 hr 15 min'", max_length=50)),
                ('servings', models.IntegerField(default=4, help_text='Number of people this recipe serves')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('cuisine', models.CharField(help_text="e.g., 'Mediterranean', 'Indian', 'Italian'", max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(help_text="e.g., '1 cup', '2 large', '1 tsp'", max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='recipes.recipe')),
            ],
        ),
    ]
